### ISSUE TITLE
Fork the mPDF project and create a new organization around it

### ISSUE THREAD

**Issue by mikealmond** [finwe/mpdf#20]
Following the discussions on the forum, I propose that this repo become a new project to allow contributions from the community—while still adhering to the original GPL licence. 

The author has even mentioned that he would be open to supporting a project like this if enough people contributed. 

> [...]The best suggestion I can make is that you contact the others who have posted mPDF on github and see if you can get them to agree to have one project. You are welcome then to post messages here about a unified project. If you can manage this, I would certainly consider working co-operatively with the project, but with no commitment.
> 
> http://www.mpdf1.com/forum/discussion/1071#Item_2

Thoughts?

### Other forum requests for an official public repository
http://www.mpdf1.com/forum/discussion/1071
http://www.mpdf1.com/forum/discussion/1248
http://www.mpdf1.com/forum/discussion/931/development-suspended-final-release
http://www.mpdf1.com/forum/discussion/293

**Comment by finwe** [comment]
There is now a collaborative effort at http://github.com/mpdf/mpdf repository.
