### ISSUE TITLE
Image not showing on live server

### ISSUE THREAD

**Issue by swapnil-woxi** [finwe/mpdf#42]
I have use this mpdf functionality. It is properly working on localhost ,but gives error on live for 
mPDF error: IMAGE Error (http://www.universalmanagement.co.in/alpha/ofr_capture_data/noimage.jpg): Could not find image file

I have check url of image is also properly working.

**Comment by finwe** [comment]
Please consult [official support forum](http://www.mpdf1.com/mpdf/forum/) as this repository is intended only as composer/packagist provider.

**Comment by swapnil-woxi** [comment]
I have try for login to mpdf forum , but gives message permission denied
