### ISSUE TITLE
PHP Fatal error:  Class 'mPDF' not found

### ISSUE THREAD

**Issue by jan1980** [finwe/mpdf#44]
Hi guys, newbie here. I receive this error, although I think I'm correctly including `mpdf.php` into the "caller" script:

```
PHP Fatal error:  Class 'mPDF' not found in /home2/public_html/website/mpdf/testing/caller.php on line 35
```

On line 35, I have this: `$mpdf=new mPDF();`

I tried with and without commas:

```
$mpdf=new mPDF();
```
```
$mpdf=new mPDF('');
```

I'm following the example here to place a button on every page, and transforming it into a PDF: http://mpdf1.com/manual/index.php?tid=457

Do you know what's going on?
Thanks,
Jan

**Comment by jan1980** [comment]
Looking good, I changed the path following the Basic example in the installation to this (after commenting out line 4 and 6):

`include("../mpdf.php");`

...and also added a 'c' inside the class:

`$mpdf=new mPDF('c');`

The CSS styles are not wrking though, even if I specified a 'print' stylesheet:

`$mpdf->CSSselectMedia='print'; // assuming you used this in the document header`

**Comment by finwe** [comment]
Hi, please, consult [official support forum](http://www.mpdf1.com/mpdf/forum/) as this is an unofficial repository only.
